name: Unity MCP — Desktop Parity

on:
  workflow_dispatch: {}

jobs:
  desktop-parity:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - name: Install Python + uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.11'

      - name: Detect Anthropic key
        id: detect_key
        run: |
          if [ -n "${{ secrets.ANTHROPIC_API_KEY }}" ]; then echo "has_key=true" >> "$GITHUB_OUTPUT"; else echo "has_key=false" >> "$GITHUB_OUTPUT"; fi

      - name: Run Claude (desktop-parity)
        uses: anthropics/claude-code-base-action@beta
        if: steps.detect_key.outputs.has_key == 'true'
        with:
          claude_args: |
            --mcp-config .claude/mcp.json
            --allowedTools "mcp__unity__find_in_file,mcp__unity__list_resources,mcp__unity__read_resource"
            --disallowedTools "TodoWrite,PlannerTool,SubagentSpawn,WebSearch,Bash,Read,Write,Edit,MultiEdit,NotebookEdit,KillBash"
            --model "claude-3-7-sonnet-20250219"
            --max-turns 10
            --timeout-minutes 15
          prompt_file: .claude/prompts/nl-unity-suite.md
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Write MCP config (.claude/mcp.json)
        run: |
          set -eux
          mkdir -p .claude
          cat > .claude/mcp.json <<'JSON'
          {
            "mcpServers": {
              "unity": {
                "command": "uv",
                "args": ["run","--directory","UnityMcpBridge/UnityMcpServer~/src","python","server.py"],
                "transport": { "type": "stdio" },
                "env": { "PYTHONUNBUFFERED": "1", "MCP_LOG_LEVEL": "debug" }
              }
            }
          }
          JSON
