name: Claude NL suite (Unity live)

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nl-suite:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Detect Anthropic key (env)
        run: |
          if [ -n "${{ secrets.ANTHROPIC_API_KEY }}" ]; then echo "ANTHROPIC_OK=true" >> "$GITHUB_ENV"; else echo "ANTHROPIC_OK=false" >> "$GITHUB_ENV"; fi
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # --- Python env for MCP server (uv) ---
      - uses: astral-sh/setup-uv@v4
        with: { python-version: '3.11' }
      - name: Install MCP server
        run: |
          set -eux
          uv venv
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> "$GITHUB_ENV"
          echo "$GITHUB_WORKSPACE/.venv/bin" >> "$GITHUB_PATH"
          if [ -f UnityMcpBridge/UnityMcpServer~/src/pyproject.toml ]; then
            uv pip install -e UnityMcpBridge/UnityMcpServer~/src
          elif [ -f UnityMcpBridge/UnityMcpServer~/src/requirements.txt ]; then
            uv pip install -r UnityMcpBridge/UnityMcpServer~/src/requirements.txt
          fi

      # --- Prime Unity license on host (fast no-op) ---
      - name: Prime Unity license (host)
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE:  ${{ secrets.UNITY_LICENSE }}   # optional ULF contents
          UNITY_EMAIL:    ${{ secrets.UNITY_EMAIL }}     # optional sign-in
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL:   ${{ secrets.UNITY_SERIAL }}    # optional serial
        with:
          projectPath: TestProjects/UnityMCPTests
          testMode: editmode
          customParameters: -runTests -testFilter __NoSuchTest__ -batchmode -nographics

      # --- Start headless Unity that stays up (bridge enabled) ---
      - name: Start Unity (persistent bridge)
        run: |
          set -eux
          mkdir -p "$HOME/.unity-mcp" \
                   "$HOME/.local/share/unity3d" \
                   "$HOME/.config/unity3d" \
                   "$HOME/.cache/unity3d"
          docker run -d --name unity-mcp \
            --network host \
            -e UNITY_MCP_ALLOW_BATCH=1 \
            -e UNITY_MCP_STATUS_DIR=/root/.unity-mcp \
            -v "${{ github.workspace }}:/workspace" -w /workspace \
            -v "$HOME/.local/share/unity3d:/root/.local/share/unity3d" \
            -v "$HOME/.config/unity3d:/root/.config/unity3d" \
            -v "$HOME/.cache/unity3d:/root/.cache/unity3d" \
            -v "$HOME/.unity-mcp:/root/.unity-mcp" \
            unityci/editor:2021.3.45f1-base-3 \
            /opt/unity/Editor/Unity \
              -batchmode -nographics -logFile - \
              -projectPath /workspace/TestProjects/UnityMCPTests \
              -executeMethod UnityMcpBridge.Editor.UnityMcpBridge.StartAutoConnect

      - name: Wait for Unity bridge
        run: |
          set -eux
          docker logs -f unity-mcp & LOGPID=$!
          deadline=$((SECONDS+420))
          while [ $SECONDS -lt $deadline ]; do
            # Prefer a log marker; adjust to your actual log text:
            if docker logs unity-mcp 2>&1 | grep -qE "MCP Bridge listening|Bridge ready|Server started"; then
              echo "Bridge ready (logs)"; kill $LOGPID || true; exit 0
            fi
            # Fallback: JSON + socket probe (optional)
            PORT=$(python -c "import os,glob,json,sys; b=os.path.expanduser('~/.unity-mcp'); fs=sorted(glob.glob(os.path.join(b,'unity-mcp-status-*.json')), key=os.path.getmtime, reverse=True); print(json.load(open(fs[0]))['unity_port']) if fs else sys.exit(1)" 2>/dev/null || true)
            if [ -n "${PORT:-}" ] && timeout 1 bash -lc "exec 3<>/dev/tcp/127.0.0.1/$PORT && head -c 256 <&3 | tr -d '\0' | grep -q 'FRAMING=1'"; then
              echo "Bridge ready on port $PORT"; kill $LOGPID || true; exit 0
            fi
            sleep 2
          done
          echo "Bridge not ready in time"
          kill $LOGPID || true
          docker logs unity-mcp || true
          exit 1

      # --- Claude suites ---
      - name: Claude startup sanity
        id: claude_startup
        uses: anthropics/claude-code-base-action@beta
        if: env.ANTHROPIC_OK == 'true'
        with:
          prompt_file: .claude/prompts/nl-startuptest.md
          allowed_tools: >
            Bash(git:*),Read,Write,LS,Glob,Grep,
            ListMcpResourcesTool,ReadMcpResourceTool,
            mcp__unity__script_apply_edits,mcp__unity__apply_text_edits,
            mcp__unity__create_script,mcp__unity__delete_script,
            mcp__unity__validate_script,mcp__unity__manage_script,
            mcp__unity__manage_scene,mcp__unity__manage_editor,
            mcp__unity__manage_gameobject,mcp__unity__manage_asset,
            mcp__unity__manage_shader,mcp__unity__read_console,
            mcp__unity__execute_menu_item,mcp__unity__list_resources,
            mcp__unity__read_resource,mcp__unity__find_in_file
          mcp_config: |
            {
              "mcpServers": {
                "unity": {
                  "command": "uv",
                  "args": ["run","--active","--directory","UnityMcpBridge/UnityMcpServer~/src","python","server.py"],
                  "transport": { "type": "stdio" },
                  "env": {
                    "PYTHONUNBUFFERED": "1",
                    "MCP_LOG_LEVEL": "debug",
                    "UNITY_PROJECT_ROOT": "${{ github.workspace }}/TestProjects/UnityMCPTests"
                  }
                }
              }
            }
          model: "claude-3-7-sonnet-20250219"
          max_turns: "8"
          timeout_minutes: "7"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Claude NL/T suite
        uses: anthropics/claude-code-base-action@beta
        if: env.ANTHROPIC_OK == 'true' && steps.claude_startup.outcome == 'success'
        with:
          prompt_file: .claude/prompts/nl-unity-claude-tests-mini.md
          allowed_tools: >
            Bash(git:*),Read,Write,LS,Glob,Grep,
            ListMcpResourcesTool,ReadMcpResourceTool,
            mcp__unity__script_apply_edits,mcp__unity__apply_text_edits,
            mcp__unity__create_script,mcp__unity__delete_script,
            mcp__unity__validate_script,mcp__unity__manage_script,
            mcp__unity__manage_scene,mcp__unity__manage_editor,
            mcp__unity__manage_gameobject,mcp__unity__manage_asset,
            mcp__unity__manage_shader,mcp__unity__read_console,
            mcp__unity__execute_menu_item,mcp__unity__list_resources,
            mcp__unity__read_resource,mcp__unity__find_in_file
          mcp_config: |
            {
              "mcpServers": {
                "unity": {
                  "command": "uv",
                  "args": ["run","--active","--directory","UnityMcpBridge/UnityMcpServer~/src","python","server.py"],
                  "transport": { "type": "stdio" },
                  "env": {
                    "PYTHONUNBUFFERED": "1",
                    "MCP_LOG_LEVEL": "debug",
                    "UNITY_PROJECT_ROOT": "${{ github.workspace }}/TestProjects/UnityMCPTests"
                  }
                }
              }
            }
          model: "claude-3-7-sonnet-20250219"
          max_turns: "16"
          timeout_minutes: "12"
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

      # --- Always stop Unity ---
      - name: Stop Unity
        if: always()
        run: |
          docker logs unity-mcp || true
          docker rm -f unity-mcp || true
