name: Unity MCP — QuickProbe

on:
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  quickprobe:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python + uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: '3.11'

      # Optional but makes server startup snappier and consistent
      - name: Editable install of UnityMcpServer
        run: |
          set -eux
          uv venv
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> "$GITHUB_ENV"
          echo "$GITHUB_WORKSPACE/.venv/bin"       >> "$GITHUB_PATH"
          uv pip install -e "UnityMcpBridge/UnityMcpServer~/src"

      - name: Run QuickProbe
        uses: anthropics/claude-code-base-action@beta
        with:
          prompt_file: .claude/prompts/mcp-quickprobe.md
          # Wildcard so sub-sessions/subagents also have access
          allowed_tools: mcp__unity__*,ListMcpResourcesTool,ReadMcpResourceTool
          model: claude-3-7-sonnet-20250219
          max_turns: 6
          timeout_minutes: 5
          mcp_config: |
            {
              "mcpServers": {
                "unity": {
                  "command": "uv",
                  "args": ["run","--active","--directory","UnityMcpBridge/UnityMcpServer~/src","python","server.py"],
                  "transport": { "type": "stdio" },
                  "env": {
                    "PYTHONUNBUFFERED": "1",
                    "MCP_LOG_LEVEL": "debug",
                    "UNITY_MCP_PROJECT_ROOT": "."
                  }
                }
              }
            }
          settings: |
            {
              "permissionMode": "allow",
              "defaultMode": "bypassPermissions",
              "permissionStorage": "none",
              "autoApprove": ["mcp__unity__*"]
            }
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}

      - name: Upload QuickProbe log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: quickprobe-claude-execution
          path: /home/runner/work/_temp/claude-execution-output.json
          if-no-files-found: warn
